### ISSUE TITLE
CTD bug

### ISSUE THREAD

**Issue by TheGodBOOMZ** [Glampi42/ONI-Mods#1] opened 2023-09-12 17:47 UTC
I'm not sure what caused this so I apologize for being unable to give further information. I was planning out a dig when the game crashed.

NullReferenceException

AdvancedFlowManagement.Patches.CrossingsUpdates_Patches.PostProcessNetworksRebuild (System.Collections.Generic.ICollection`1[T] allUpdatedCells, System.Boolean firstUpdate, ConduitFlow conduitFlow) (at <3fbccb10589c439391647b3d6940ac79>:0)
AdvancedFlowManagement.Patches.Main_Patches+OnNetworksRebuilt_Patch.Postfix (System.Collections.Generic.IList`1[T] networks, System.Collections.Generic.ICollection`1[T] root_nodes, ConduitFlow __instance) (at <3fbccb10589c439391647b3d6940ac79>:0)
(wrapper dynamic-method) ConduitFlow.ConduitFlow.OnUtilityNetworksRebuilt_Patch1(ConduitFlow,System.Collections.Generic.IList`1<UtilityNetwork>,System.Collections.Generic.ICollection`1<int>)
UtilityNetworkManager`2[NetworkType,ItemType].Update () (at <ad882e55d8ac49379773540ee16f428f>:0)
Game.LateUpdate () (at <ad882e55d8ac49379773540ee16f428f>:0)

Build: U48-568201-SD

**Comment by Glampi42** [comment] 2023-09-14 18:15
Right now I am not sure, what caused that crash. However, if in the future you experience a similar crash, then please send the new error message again, because I updated the mod(see v1.1.3) to now give more info about the crash which will hopefully help allocate the issue.

**Comment by Glampi42** [comment] 2023-09-14 18:17
Right now I am not sure, what caused that crash. However, if in the future you experience a similar crash, then please send the new error message again, because I updated the mod(see v1.1.3) to now give more info about the crash which will hopefully help allocate the issue.

I accidentially closed the issue xD I am new to GitHub, I'm sorry

**Comment by Glampi42** [comment] 2023-09-28 05:35
Since it's been two weeks and noone reported same error as well as I couldn't reproduce it, I'm closing the issue for now. In case you ever encounter the same-looking error, feel free to just open a new issue.

**Closed by Glampi42** 2023-09-28 05:35 UTC
